FROM ghcr.io/cross-rs/armv7-unknown-linux-musleabihf:main

RUN apt-get update && \
  apt-get --assume-yes install \
  protobuf-compiler \
  libprotobuf-dev

ENV MUSL_PREFIX=arm-linux-musleabihf
ENV SQLITE_VERSION=3490100
ENV ZLIB_VERSION=1.3.1

RUN echo "Building zlib" && \
  cd /tmp && \
  curl -fLO "https://zlib.net/zlib-$ZLIB_VERSION.tar.gz" && \
  tar xvzf "zlib-$ZLIB_VERSION.tar.gz" && cd "zlib-$ZLIB_VERSION" && \
  CC=$MUSL_PREFIX-gcc AR=$MUSL_PREFIX-ar RANLIB=$MUSL_PREFIX-ranlib \
  ./configure --static --prefix=/usr/local/$MUSL_PREFIX-target && \
  make && make install && rm -r /tmp/*

RUN echo "Building SQLite" && \
  cd /tmp && \
  curl -fLO "https://sqlite.org/2025/sqlite-autoconf-$SQLITE_VERSION.tar.gz" && \
  tar xvzf "sqlite-autoconf-$SQLITE_VERSION.tar.gz" && cd "sqlite-autoconf-$SQLITE_VERSION" && \
  env CC=$MUSL_PREFIX-gcc ./configure --host=arm-linux --enable-static --prefix=/usr/local/$MUSL_PREFIX-target && \
  make && make install && rm -r /tmp/*

ENV PKG_CONFIG_PATH=/usr/local/$MUSL_PREFIX-target/lib/pkgconfig
